# Generated by Django 4.2.2 on 2023-06-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.CharField(max_length=255),
        ),
    ]
