# Generated by Django 4.2.2 on 2023-06-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_alter_profile_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('linkedin', models.CharField(max_length=255)),
                ('Qualification', models.CharField(max_length=255)),
                ('objective', models.CharField(max_length=255)),
                ('github', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
